-- 코드를 입력하세요
SELECT
    P.PRODUCT_CODE,
    SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
    -- 매출액
    FROM PRODUCT P
    JOIN OFFLINE_SALE O ON P.PRODUCT_ID= O.PRODUCT_ID
    GROUP BY P.PRODUCT_CODE
    -- 상품 코드별 
    ORDER BY SALES DESC, P.PRODUCT_CODE ASC;