-- 코드를 입력하세요
-- PRODUCT_CODE를 앞에서 둘째자리까지만 잘라서 표기하므로 SUBSTR 함수를 사용한다.
SELECT
    SUBSTR(PRODUCT_CODE, 1,2) AS CATEGORY,
    COUNT(PRODUCT_CODE) AS PRODUCTS
    FROM PRODUCT
    GROUP BY SUBSTR(PRODUCT_CODE, 1,2)
    ORDER BY CATEGORY;
    